title: Hardware and stuff
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
domain: io32.dev
url: "https://io32.dev"
github_username:  zaporozhets

# Build settings
theme: minima
plugins:
  - jekyll-feed

